### ISSUE TITLE
Error while executing on Docker

### ISSUE THREAD

**Issue by rafanog** [auth0-community/ember-simple-auth-auth0#101]
There's an error shown while executing the sample through docker 

![image](https://user-images.githubusercontent.com/15782359/34785229-e3d2c44e-f606-11e7-94c4-894818746d4c.png)

![image](https://user-images.githubusercontent.com/15782359/34785276-04b3fa0c-f607-11e7-9d4b-9a89bd7c53c5.png)

**Comment by paulioceano** [comment]
@XaserAcheron @aaguiarz Got the exact same error.

The sample used is the one downloaded in this quickstart: https://auth0.com/docs/quickstart/spa/ember

**Comment by XaserAcheron** [comment]
Hmm, that sample's definitely out of date, unfortunately. :(

There's a slightly-more-minimal quickstart guide in the [README.md](https://github.com/auth0-community/ember-simple-auth-auth0/blob/develop/README.md) of this repo, but it's up to date. Give that a shot and see if it works out for y'all. It's all I can suggest from here, I'm afraid.
