### ISSUE TITLE
call logout method

### ISSUE THREAD

**Issue by miguelcobain** [auth0-community/ember-simple-auth-auth0#104]
Shouldn't we be calling the logout method of lock.js?
https://auth0.com/docs/libraries/lock/v11/api#logout-

**Comment by medokin** [comment]
We should. Currently if the User logs out, Auth0 remembers the last login and provides a One-Click login.

Effectively, the user cannot log out if rememberLastLogin option is set to `true` (thats the default!)  
https://auth0.com/docs/libraries/lock/v11/configuration#rememberlastlogin-boolean-

**Comment by miguelcobain** [comment]
@medokin seems like the idea is to call the `logout` method on the auth0 service.
It calls invalidateSession for you and hits auth0's logout url.
