### ISSUE TITLE
SPA + API setup - how to authorise the API?

### ISSUE THREAD

**Issue by joshuaob** [auth0-community/ember-simple-auth-auth0#110]
Just wondering how, where and when the jwt authoriser should be called, when using a SPA + API setup. The authenticator works fine and returns an access token in the url as expected, but the app just stays on that page with the token in the URL. I have tried called the authoriser right after the authenticator and within a 'then' block with no luck. has anyone successfully implemented the oauth implicit grant flow using this package, if so please help.

**Comment by joshuaob** [comment]
please delete as I have not heard from anyone, ill try something else.

**Comment by XaserAcheron** [comment]
This is a volunteer project maintained by people in their spare time, not a full time job. I hadn't had a chance to take a close look at this yet, nor do I know what to suggest off the top of my head based on this report alone (it's rather vague). What have you tried? Do you have sample code? And so forth.

[Not that I'll be able to answer presently; I'm quite busy.]
