### ISSUE TITLE
Impersonation not working correctly

### ISSUE THREAD

**Issue by mrship** [auth0-community/ember-simple-auth-auth0#111]
Hello there,

I'm working with `4.0.0.beta2` in order to upgrade to lock v11. I've upgraded from 3.1.0 where impersonation was working fine in our app. With 4.0.0.beta2, while I can log in via Social login or username/password, trying to log in via impersonation doesn't work. I get the following error:

```
error: "invalid_token", errorDescription: "`state` does not match."
```

I have added `enableImpersonation: true` to the config setup and, as I say, impersonation was working fine under 3.1.0, so I'm not sure if this is an issue here, or in the auth0 libraries.

Any help would be appreciated and thanks for the great work you've done on the library.

**Comment by dbinetti** [comment]
@mrship see #107

**Comment by dbinetti** [comment]
oh, sorry!  just saw you saw that....

**Comment by XaserAcheron** [comment]
I'm not quite sure what can be done here. The `enableImpersonation` flag is just getting passed into auth0.js (i.e. a black box), since that's the [official fix](https://github.com/auth0/auth0.js/issues/683) for a thing.

A question: When generating the impersonate link, are you setting the `state` field to something or leaving it blank? This may help diagnose it, though at the end of the day this is over my head. It's working for me.

**Comment by mrship** [comment]
I'm leaving the `state` field empty and accepting the defaults that the Auth0 UI provides. This is the same approach we were using under lock v10 previously. I'll dig deeper and see if I can work out why the state doesn't match.

**Comment by mrship** [comment]
It turns out that we weren't using the correct `ApplicationRouteMixin` - we were using the one from ember-simple-auth. 😱 

I have other issues now that I need to address, but impersonation appears to be working properly. 

Apologies for the noise.

**Comment by XaserAcheron** [comment]
Welp! That would do it! And no worries, it happens. It's always better to report an issue and go "whoops" than to not report it and risk having something nefarious lurk about.

Hope everything else goes well!
