### ISSUE TITLE
"Last time you logged in" does not store the JWT in the session

### ISSUE THREAD

**Issue by roschaefer** [auth0-community/ember-simple-auth-auth0#112]
I'm trying the new Lockv11 features with passwordless login. Thank you @XaserAcheron, by the way.

But when I

1. sign in the first time with e.g. `google-oauth2`
2. click login in one more time
3. I see "Last time you signed in via..." google in my case
4. I click on the button
5. I see "Thanks for logging in" (you're welcome :expressionless:)
6. But I'm not logged in

![rundfunk-mitbestimmen - mozilla firefox_184](https://user-images.githubusercontent.com/2110676/37793462-0db755be-2e0f-11e8-9da0-1be75a782668.png)

**Comment by XaserAcheron** [comment]
Whew, sorry about this. There was some legacy code in the Passwordless authenticator that was indeed breaking the "Last time you logged in with..." button. Should be fixed in `4.0.0-beta.3`, which will hit shortly.

**Comment by roschaefer** [comment]
Thank you so much :heart: I'll test this

**Comment by XaserAcheron** [comment]
Glad to help! Sorry for cutting it so darn close to the switchover date.

Just published `4.0.0-beta.3`. I'll probably go ahead and cut a proper release form this version sometime today -- there's always room for bugfix patches. ;)

**Comment by roschaefer** [comment]
works! :1st_place_medal:
