### ISSUE TITLE
Can't find element with id ember<x>

### ISSUE THREAD

**Issue by donaldwasserman** [auth0-community/ember-simple-auth-auth0#127]
Hello - 

I'm not sure this is a bug or a problem with how we've implemented this, after our login flow, we keep getting these `can't find element with id ember<x>` where x is usually less than 10. 

we have a component that we're calling the `auth0-lock` authenticator in the `didRender` hook. 

Is there an better way to avoid this error?

**Comment by XaserAcheron** [comment]
Can you reproduce this in a small sample project? There's unfortunately not much I can investigate from this side without more details.

**Comment by donaldwasserman** [comment]
Sorry - after I went through to create a limited test case, I realized I was using the wrong component hook to insert the lock.js code.
