### ISSUE TITLE
Not working as expected?

### ISSUE THREAD

**Issue by medokin** [auth0-community/ember-simple-auth-auth0#128]
I'm using this library for a long time, but its always kind of hacky to get it working.

For Example:
Using lock:

```js
    login() {
      const lockOptions = {
        auth: {
          params: {
            scope: 'openid profile email'
          },
          responseType: 'token',
        },
        theme: {
          logo: '/android-chrome-192x192.png',
          primaryColor: '#0b424a'
        };
        rememberLastLogin: true,
        autofocus: true,
        autoclose: true,
      };

      get(this, 'session').authenticate('authenticator:auth0-lock', lockOptions);
    },
```
User enters the credentials, and get redirected to:
`http://localhost:4200/#access_token=Z20KOqmDmLAbICco9h6mwaBD-bRj6klp&scope=openid%20profile%20email&expires_in=7200&token_type=Bearer&state=9vtJ_4FmwdVm52PLqAqX592uy8eZcGDI`

And nothing happens until the user hits `Login` again and the lock opens. Suddenly the user is logged in. Hash-Data from URL dissapears.

![2018-07-13_14-54-44](https://user-images.githubusercontent.com/456683/42692680-bf3f0bd8-86ac-11e8-86d2-cb0482ba6f38.gif)

Does someone know why that happens? Am I missing something?

**Comment by medokin** [comment]
Nevermind... 

```js
  beforeModel() {
    this._super(...arguments); // <- this line was missing
    this.get('moment').setLocale('de');
  }
```

**Comment by XaserAcheron** [comment]
Heh, oh no! :(

If it makes you feel better, I ran into this myself when I first installed this addon. It's almost a rite of passage. :P

[Admittedly there is _quite_ a bit of logic in the application controller that I can't help but think could live elsewhere. But that's just me musing a bit.]
