### ISSUE TITLE
showLock function is trying and failing to authorize

### ISSUE THREAD

**Issue by andrewcallahan** [auth0-community/ember-simple-auth-auth0#131]
I'm doing an upgrade to the new version (I'm on the `develop` branch due to the bug on master) and am using the `showLock` function in order to embed the login form into the web page, instead of having the traditional lock.js popup.

This is the code I added to make that happen, and it does work and I'm able to log in.
```
this.get('auth0').showLock(lockOptions, config['ember-simple-auth'].auth0.clientID, config['ember-simple-auth'].auth0.domain, false);
```

However, when I'm logged out every time `showLock` runs, it sends an HTTP request to Auth0 and comes back with a 400 error. It's also taking a very long time to load the lock.js itself - possibly as a result of this error, but it could be something slower in lock 11 - I'm really not sure.

Anyway, here is what the requested URL is like:
`https://my-domain.auth0.com/authorize?client_id=9834jnxfsf09suad30r430ii23p9234234s2&response_type=token%20id_token&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fcallback&scope=openid%20profile%20email&connection=google-oauth2&state=UBIUH(#HNJSKJN23jnd23sdf&nonce=Y*Huihsadufh9a8sdyf98saduf&response_mode=web_message&prompt=none&auth0Client=eyaskdjhfasodhfo8ur8oqwuroiwhdfh29843uoizdfjoiausdjfoinasfjkaue09r`

I don't think this HTTP request during `showLock` is desired behavior, but am not sure where in the `showLock` function this URL is being requested at, or how to prevent it from happening.

**Comment by XaserAcheron** [comment]
The `showLock` function doesn't make any direct HTTP requests -- it just creates a Lock and wires it up with `ember-simple-auth`'s authentication flow. Whatever this HTTP request is, it's Lock making the call, not this addon.

Calling `showLock` directly is rather unusual usage anyway, since that sidesteps the entire `ember-simple-auth` flow. If the intent is to embed the form, you can do that with the authenticator by passing in the `container` property to the options hash when calling `authenticate`, like so:

```html
{!-- template.hbs --}
<div id="lockEmbed"></div>
```

```js
    // component.js / controller.js / whichever

    // ...
    const lockOptions = {
     container: 'lockEmbed'
     // ...
    };

    this.get('session').authenticate('authenticator:auth0-lock', lockOptions);
    // ...
```

[Note: the above is an untested fragment, but there's the gist.]

If this is still happening, could you post the response body from the 400 error? That would shed more light about what's happening here. I don't want to be a useless git and point a finger elsewhere without at least helping take a look at what's up. :P

**Comment by andrewcallahan** [comment]
@XaserAcheron I will look into this, thanks for your super helpful reply!

**Comment by andrewcallahan** [comment]
Haven't had time to revisit this until now - but I was able to successfully replace
```
this.get('auth0').showLock(lockOptions, config['ember-simple-auth'].auth0.clientID, config['ember-simple-auth'].auth0.domain, false);
```
with the much more standard
```
this.get('session').authenticate('authenticator:auth0-lock', lockOptions);
```

However, I'm still getting the same 400 error (there is no response body).

I made a brand new Ember 3.3 app, installed `ember-simple-auth-auth0`, and pasted in the application route, controller, and template from the README.

Here is that repo: https://github.com/andrewcallahan/test-auth-app

I went ahead and changed the environment file to use my credentials, and started up the app. Then I clicked the login button and Lock pops up and I immediately get that same 400 error as before.

I'm not sure if this is an issue with lock, or with the addon, but I'm now certain it isn't my app that is the cause. I don't think it is desired behavior to attempt to authenticate the instant lock is shown, but maybe I'm wrong and this is just how things are supposed to work?

**Comment by andrewcallahan** [comment]
I think I have solved it! I looked at all the hidden console.log messages and saw one that suggested that I add `http://localhost:4200` to the `Allowed Web Origins` on Auth0, which I did. Now the problem is gone. Looks like this configuration requirement was added in between the last time I upgrade and now. Thanks again for the help!

**Comment by XaserAcheron** [comment]
Glad you've got it all figured out! Apologies for not being too much help.
