### ISSUE TITLE
"Minified development build of React" error is back

### ISSUE THREAD

**Issue by XaserAcheron** [auth0-community/ember-simple-auth-auth0#136]
Looks like the "minified development build of React" bug is back (originally fixed in #90). Something about the `autoImport` config is probably off.

**Comment by XaserAcheron** [comment]
I could really use a second pair of eyes on this, if anyone's curious to take a look. It _looks_ like the setup is correct, but it ain't working and I'm not sure how to trace what `ember-auto-import`'s doing just yet (Broccoli is an arcane beast).

**Comment by joshuaob** [comment]
I tried running this package locally with my application using ```npm link```, when deploying to staging or production using ```ember-cli-deploy```, the value of ```EmberAddon.env()``` is always development.  It seems like I am chasing my tail trying to import the parent apps config into the addon config, not sure how to merge them if possible.

**Comment by timhaines** [comment]
It looks like [env()](https://ember-cli.com/api/files/lib_broccoli_ember-app.js.html#LINENUM_463) returns the value of process.env.EMBER_ENV, or `development` if that's not set.  So if you set EMBER_ENV=production during build time, does that do what you need @joshuaob?

**Comment by timhaines** [comment]
@joshuaob At this stage I don't know - I'm just trying to narrow things down a little.  :)  EMBER_ENV and --environment to behave a little differently, so maybe a bug there is impacting this.

**Comment by XaserAcheron** [comment]
If changing `EmberAddon.env()` to `"production"` really fixes the issue, I'm tempted to just hardcode the string and call it a day. This is a really silly situation and I can't imagine what benefit there is to using a development build of React in the context of this addon.

If that's indeed the trouble, then I'm super-confused on why this broke. Maybe the switch to `ember-auto-import` is just a red herring, but that just deepens the mystery. :(

Either way, this part of addon should definitely Just Work™ without any sort of tweaks in apps that use it, so I'll be sure to get it fixed in some way or form.

**Comment by timhaines** [comment]
@XaserAcheron @joshuaob I can confirm that [updating out build pipeline](https://github.com/percy/percy-web/pull/730) to specify EMBER_ENV=production as well as passing --environment=production solved this problem for us.

**Comment by joshuaob** [comment]
I added `ENV.EMBER_ENV=production` in my config/environment.js under the production build config and it did not work.

However, prefixing the deploy command with EMBER_ENV=production worked as shown below
`EMBER_ENV=production ember deploy staging` 

I have no idea which "env" value the addon is using versus what the app is using but I think this is a quick fix for now.

**Comment by XaserAcheron** [comment]
Thanks @joshuaob and @timhaines for investigating this! I decided to just set the string to `'production'` addon-side, and it seems to have fixed everything up. PR incoming, once Travis has his way with things.

**Comment by XaserAcheron** [comment]
This ought to be fixed in the next release -- for real this time.
