### ISSUE TITLE
Hint is being overflowed

### ISSUE THREAD

**Issue by EUGinsane** [auth0-community/ember-simple-auth-auth0#158]
Hi currently I am facing this bug on the UI

![image](https://user-images.githubusercontent.com/30293222/56009483-1848ef80-5d0a-11e9-806a-f9ef4cd5355a.png)

Any pro tips to fix this one ? Thanks.

**Comment by EUGinsane** [comment]
I can fix with a little trick with JS

**Comment by XaserAcheron** [comment]
It'd be best to file an issue at [Lock's repo](https://github.com/auth0/lock/issues) for this -- this addon simply links Lock and `ember-simple-auth` together, and it doesn't touch Lock's styling or behavior in any way.
