### ISSUE TITLE
Does this addon fully support Silent Authentication/Renew token ?

### ISSUE THREAD

**Issue by EUGinsane** [auth0-community/ember-simple-auth-auth0#159]
As the question described, because I don't see any guide for this in README. Thanks

**Comment by XaserAcheron** [comment]
Yep, it's supported in the 4.2.0-alpha releases (docs aren't quite done yet). There's a couple of settings to add to your environment.config which are (for now) documented at the top comment in #137 -- hopefully that's enough to get started.

**Comment by EUGinsane** [comment]
Thanks @XaserAcheron, really appreciate that

**Comment by XaserAcheron** [comment]
Closing this, but I've opened #162 as a note to add docs for Silent Auth.
