### ISSUE TITLE
Lost authenticated session when closing the browser

### ISSUE THREAD

**Issue by EUGinsane** [auth0-community/ember-simple-auth-auth0#161]
Everything works just fine but it seems like authenticated session is lost when closing the browser. After I logged in successfully, I closed the browser immediately and re-open it after that, I had to login again. Have anyone faced this issue before ? Thanks.

**Comment by XaserAcheron** [comment]
Could you post a runnable sample project showing the issue?

**Comment by EUGinsane** [comment]
sry @XaserAcheron for disturbing you too much, but this is an invalid bug, it is because I did not to set the `cookieExpirationTime` a specific time. It was always `null` so it got deleted after I closed the browser. My apologies.

**Comment by XaserAcheron** [comment]
No worries! Glad you've got it working!

My apologies for not being too useful in helping solve things. This addon is pretty simple in theory, but it links together quite a few complex parts with a lot of configuration, so it's generally pretty tough to reproduce from here.
