### ISSUE TITLE
Redirect_uri error when using GitHub & dummy app

### ISSUE THREAD

**Issue by muziejus** [auth0-community/ember-simple-auth-auth0#164]
Hi,

I've successfully implemented the basic "get authorization code" part of ember-simple-auth & torii as indicated [in this guide](https://github.com/simplabs/ember-simple-auth/blob/master/guides/auth-torii-with-github.md) with a different app.

When I try to use Auth0 with the dummy app for this repo, however, I can't get past GitHub's redirect uri error, which means that I don't even get an opportunity to authorize my application (which I can already do w/ basic ember-simple-auth & torii). Presumably, I'm missing something, but changing GitHub's callback url between:

`http://localhost:4200`
`http://localhost:4200/login`
`https://<tenant>.auth0.com`

just perpetuates the error:

`http://localhost:4200/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=<STATE>`

The only change I've made to the dummy app is feeding in my own auth0 clientID and domain.

Any ideas?

**Comment by muziejus** [comment]
I enabled all cookies, etc., and was able to get past authorization when I wired in a database connection on Auth0, which at least takes me to the protected route before redirecting me back to the index route with an `UnauthorizedError: jwt malformed` at 102:22 of `express-jwt/lib/index.js`

**Comment by muziejus** [comment]
So maybe there are two problems.

**Comment by XaserAcheron** [comment]
Could you post a sample project? There isn't anything I can do to help debug this otherwise.

I'm not sure what project template you're using, but neither this repo nor the included Auth0 dependencies have `express-jwt` as a dependency, so I'm not sure how that's found its way in.

**Comment by muziejus** [comment]
Thanks. Sorry for bothering you all, since I ended up figuring out how to roll a GitHub-only solution (which is sufficient for my needs for now) with ember-simple-auth and torii:

http://github.com/muziejus/ember-simple-auth-github-octane

**Comment by XaserAcheron** [comment]
Sorry it didn't work out. :(

Hmm, for the record, I've never tested this with Octane, so I can't rule out the possibility of some incompatibility there. Just vague musings, though -- not sure if I'll get the time to play with it myself, given [recent happenings](https://github.com/auth0-community/ember-simple-auth-auth0/issues/165).

**Comment by muziejus** [comment]
Cheers and congrats, then. I was able to implement ember-simple-auth-auth0 with an earlier version of this project back when I was kicking around the idea of rewriting it in Ember the first time, so I've had some luck with the project. 

Without actually knowing much of the mechanics, I wonder if the move away from `Ember.$` is going to mess up a lot of these kinds of addons.
