### ISSUE TITLE
Move to auth0-community org

### ISSUE THREAD

**Issue by seawatts** [auth0-community/ember-simple-auth-auth0#49]

**Comment by sukima** [comment]
This is tagged v3.0.0 and package.json is at 3.0.1 does that mean porting to the official organization is a no go? Is this project still alive?

**Comment by seawatts** [comment]
Yes this project is still alive. However, I'm not sure if it will be moving over to the official org anymore.

**Comment by dbinetti** [comment]
Chris, what is the blocker on moving it?  Can I help by prodding Eugenio?
 (Meaning, is it politics or technical?)

**Comment by seawatts** [comment]
Just talked with Ryan and he said we will move it over soon.

**Comment by dbinetti** [comment]
:-)

**Comment by dbinetti** [comment]
So perhaps we can close this @seawatts?  Or do you want to package a release first?

**Comment by seawatts** [comment]
Yeah we can close this. And release soon.
