### ISSUE TITLE
Authenticator fails if oidcConformant flag is set

### ISSUE THREAD

**Issue by LeviDooley** [auth0-community/ember-simple-auth-auth0#70]
```javascript
    var lockOptions = {
      container: 'root',
      auth: {
        params: {
          scope: 'openid',
          audience: 'https://xxxxxxxx.execute-api.us-west-2.amazonaws.com/xxxxxxx/xxxxxxx/'
        },
        redirect: true,
        sso: false,
        responseType: 'token'
      },
      oidcConformant: true,
      allowSignUp: false,
      allowForgotPassword: false,
      rememberLastLogin: false
    };
```

I have this set to true because auth0 seems to be deprecating the old style of access tokens. Setting `oidcConformant` to true will switch lock to use the new flows ([/oauth/token](https://auth0.com/docs/api/authentication#resource-owner-password) in my case). The difference is that the new access tokens are in JWT format.

Anyway, I believe the issue is that your _setupLock function in the [auth0.js](https://github.com/seawatts/ember-simple-auth-auth0/blob/develop/addon/services/auth0.js#L120) service uses `lock.getProfile`, which has been deprecated according to the [docs](https://auth0.com/docs/libraries/lock/v10/api#getuserinfo-).

`getProfile()` usually still works though as long as the `lockOptions.oidcConformant` flag isn't present or set to false. However, the `getProfile` function throws an error if `oidcConformant` is set to true.

Auth0 made `getUserInfo` to replace `getProfile`, and it accepts an access token instead of an id token.
It's worth noting that one minor difference between `getUserInfo` and `getProfile` is that `authenticated.profile.user_id` is replaced with `authenticated.profile.sub`.

Anyway, this is the temporary fix I'm using for now, but I'd love to see it fixed in the official release. 😄 
```javascript
// ember-simple-auth-auth0/addon/services/auth0.js:120
  _setupLock(lock, resolve, reject) {
    lock.on('unrecoverable_error', reject);
    lock.on('authorization_error', reject);

    // lock.on('hash_parsed', resolve);
    lock.on('authenticated', (authenticatedData) => {
      if (isEmpty(authenticatedData)) {
        return reject(new Error('The authenticated data did not come back from the request'));
      }
 
      if(authenticatedData.accessToken.length > 16) {
        // Edit 
        // Checking over 16 characters because JWT tokens are longer than the old
        // 16 character opaque tokens. But it's probably better to just check the lockOptions 
        // for the oidcConformant flag instead.

        lock.getUserInfo(authenticatedData.accessToken, (error, profile) => {
          if (error) {
            return reject(error);
          }

          resolve(createSessionDataObject(profile, authenticatedData));
        });
      }
      else {
        // Original
        lock.getProfile(authenticatedData.idToken, (error, profile) => {
          if (error) {
            return reject(error);
          }

          resolve(createSessionDataObject(profile, authenticatedData));
        });
      }
    });
  },
```

**Comment by XaserAcheron** [comment]
Sorry this took so long!

I've implicitly fixed this in #96 by switching over to `getUserInfo` unconditionally. Normally I'd also port this sort of fix to the current major (3.x), but since Auth0 is deprecating the old stuff pretty aggressively, I'm holding back on doing such changes unless it's really messing with folks.
