### ISSUE TITLE
Optional Passwordless?

### ISSUE THREAD

**Issue by JackCA** [auth0-community/ember-simple-auth-auth0#76]
I believe I've come to discover that the styling injected by auth0/lock-passwordless is interfering with design changes made to the base Lock.js popup. I have [opened an issue](https://github.com/auth0/lock-passwordless/issues/137) in that repo.

In the meantime, I tried to fork this library to remove its lock-passwordless dependency but that change involved modifying core functionality rather than removing a few `import` statements.

Do you have any thoughts on whether passwordless could be optional?

Additionally, I assume there are some that would appreciate the removal a dependency that they may not be using.

**Comment by JackCA** [comment]
Just an update here: the Auth0 team has indicated that they intend to merge Passwordless into the base Lock.js project itself, so I would assume that switchover in this library will have a similar implementation.

See: https://github.com/auth0/lock-passwordless/issues/137#issuecomment-320768072

**Comment by cadeParade** [comment]
Thanks for posting this issue. We are having the same problem and removing `passwordless` is not trivial. I'll keep an eye out here.

**Comment by cadeParade** [comment]
In the meantime we may use something like this to remove the passwordless auth0 css element
`$('style:contains("auth0-lock-cred-pane")').not('#auth0-lock-style').remove()`
