### ISSUE TITLE
release soon?

### ISSUE THREAD

**Issue by dbinetti** [auth0-community/ember-simple-auth-auth0#77]
Been a while since the last release; what's the plan here @seawatts ?  Thanks

**Comment by seawatts** [comment]
Hey, sorry I haven't been working on ember stuff lately. I'll try to get around to it soon.

**Comment by dbinetti** [comment]
Hey @seawatts how about making @XaserAcheron an admin?  There's been so much work put into this it would be a shame to have it die for lack of attention....

**Comment by seawatts** [comment]
Hey yeah I think that's a great idea. I'm no longer an admin anymore however. We need to contact auth0

**Comment by dbinetti** [comment]
Who?  Is it @darkyen ?

**Comment by dja** [comment]
@darkyen Is the develop branch in good enough shape so we can have a new release supporting things like Passwordless "socialormagiclink", and fix the issues covered in the PRs? It seems that the master branch 3.0.1 release doesn't work out of the box anymore with Auth0 changes.

**Comment by XaserAcheron** [comment]
Oh, hey -- thanks for the mention earlier! I'm a silly person and missed this.

I can't guarantee a massive amount of time, but I'm using this addon actively and wouldn't mind chipping in when I can on the maintenance front.

Either way, a new release seems prudent.

**Comment by dbinetti** [comment]
despite my constant pestering, I can't get anyone at auth0 to respond to
anything anymore.  they just raised a huge round so I don't think they are
dying, but they certainly have decided to completely ignore the community.
 sad

**Comment by aaguiarz** [comment]
Hi

I apologize for the lack of attention this project has gotten from Auth0.

@XaserAcheron, we can make you an admin of the project if you are up to it. 

Regards,

Andres

**Comment by XaserAcheron** [comment]
Hi Andres,

Yup, I'm up for it.

Thanks for checking in!

**Comment by aaguiarz** [comment]
Done!

**Comment by XaserAcheron** [comment]
Thanks there!

I may not be able to get to tidy+release mode until tomorrow/Wednesday (had some stuff come up at work), but I'll get on it as soon as I can.

**Comment by XaserAcheron** [comment]
BTW, if you need my npm account to set any publishing stuff up, I'm [this guy](https://www.npmjs.com/~xaser). Behold the empty page.

**Comment by XaserAcheron** [comment]
Transparency Report no.1: I'm gearing up for a `v3.1.0` release, but I'm going to do some additional testing to make sure the upgrade path for folks on `v3.0.1` isn't too rocky (given that there's a bower-npm/yarn switch involved, and breaking dependencies is no fun). Stay tuned.

**Comment by dbinetti** [comment]
I'm just thrilled this is getting attention!  Thanks @XaserAcheron

**Comment by donaldwasserman** [comment]
@XaserAcheron If there are issues that need some attention, I have 1-2 people that can help look into/resolve them to move this along if you run into issues.

**Comment by aaguiarz** [comment]
Hey @XaserAcheron can you drop me an email? andres.aguiar@auth0.com , thanks! :)

**Comment by XaserAcheron** [comment]
@aaguiarz  E-mail dropped! Apologies for the lateness.

@donaldwasserman That'd be fantastic -- thanks! I ran into a few snags, one of which is monkey-wrenching enough that it'll trip up folks if we were to publish a release immediately, so an extra few pairs of eyes would help a lot, I think. I'll open some issues here shortly.

**Comment by XaserAcheron** [comment]
[v3.1.0](https://github.com/auth0-community/ember-simple-auth-auth0/releases/tag/v3.1.0) is live! Thanks for all the help, folks!

**Comment by dbinetti** [comment]
Thanks @XaserAcheron for your diligence in getting this over the line!
