### ISSUE TITLE
Correct credentials after 1st failed login don't work.

### ISSUE THREAD

**Issue by alex-jgr** [auth0-community/ember-simple-auth-auth0#82]
Passing reject to lock on the "authorization_error" event prevents all login attempts after a first failed login attempt, unless the page is refreshed.

The file is 
_ember-simple-auth-auth0\addon\services\auth0.js_

The issue is on line 122
`lock.on('authorization_error', reject);`

We have a custom authenticator which extends
'ember-simple-auth-auth0/authenticators/auth0-lock'

My workaround for now is to override the _authenticate_ method inside our authenticator with the following

```
authenticate (options) {
        var _this = this;
        // The Auth0 service is available here because this class is a child class of Auth0Lock,
        // so we can do the workaround for the 2nd attempt issue.
        var auth0 = this.get("auth0");
        
        const lock = auth0.getAuth0LockInstance(options);
        return new Ember.RSVP.Promise( function (resolve, reject) {
            lock.on('unrecoverable_error', reject);

            lock.on('authenticated', (authenticatedData) => {
                if (Ember.isEmpty(authenticatedData)) {
                    return reject(new Error('The authenticated data did not come back from the request'));
                }
                lock.getProfile(authenticatedData.idToken, (error, profile) => {
                    if (error) {
                        Ember.Logger.error("Error", error );
                    }

                    resolve(createSessionDataObject(profile, authenticatedData));
                });
            });

            lock.show();
        });
}


```

Please let me know if there is a better way to do this or a fix coming any time soon.
Thank you!

**Comment by miguelcobain** [comment]
I can confirm this is happening.

**Comment by miguelcobain** [comment]
My workaround was to overwrite the `app/services/auth0.js` service with:
```js
import Auth0Service from 'ember-simple-auth-auth0/services/auth0';
import createSessionDataObject from 'ember-simple-auth-auth0/utils/create-session-data-object';
import { isEmpty } from '@ember/utils';

export default Auth0Service.extend({
  _setupLock(lock, resolve, reject) {
      // lock.on('unrecoverable_error', reject);
      // lock.on('authorization_error', reject);

      // lock.on('hash_parsed', resolve);
      lock.on('authenticated', (authenticatedData) => {
        if (isEmpty(authenticatedData)) {
          return reject(new Auth0Error('The authenticated data did not come back from the request'));
        }

        lock.getUserInfo(authenticatedData.accessToken, (error, profile) => {
          if (error) {
            return reject(new Auth0Error(error));
          }

          resolve(createSessionDataObject(profile, authenticatedData));
        });
      });
    }
});
```

Notice the commented `lock.on('authorization_error', reject);` line.
It's weird. Looks like it isn't an ember-simple-auth-auth0 but rather a lock.js error.

**Comment by XaserAcheron** [comment]
Is this still happening in the latest `4.0.0` betas? I can't seem to reproduce this.

It does look fishy that the promise is rejected on `authorization_error`, since the intent is that ESA's `authenticate()` promise is unfulfilled while the Lock widget is still up. Since an authorization error doesn't dismiss the Lock, the promise really ought not be rejected -- I'm frankly surprised I'm not hitting this issue myself now that I understand what's (probably) going on.

A concerning side-thought: since the `authenticate()` promise is only rejected or resolved when Lock does something, this likely means that if you _dismiss_ the Lock pop-up, that promise just hangs in the air forever. That doesn't sound good. :/

**Comment by XaserAcheron** [comment]
Finally got around to reproducing this -- it's somewhat setup-dependent, it seems. Fix incoming.
