### ISSUE TITLE
React warning (minified development build)

### ISSUE THREAD

**Issue by XaserAcheron** [auth0-community/ember-simple-auth-auth0#88]
When running with `environment=production`, React gripes about being minified:
> Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

There's some pretty standard `webpack` boilerplate for resolving this:
```javascript
new webpack.DefinePlugin({
  "process.env": { 
     NODE_ENV: JSON.stringify("production") 
   }
})
```

Just need to find the right meta-syntax for `broccoli-webpack`.

**Comment by stfnio** [comment]
@XaserAcheron hello! I still has this warning in my production build. What can I do to get rid of it?
