### ISSUE TITLE
"Multiple copies of React" error

### ISSUE THREAD

**Issue by XaserAcheron** [auth0-community/ember-simple-auth-auth0#89]
Well, here's a doozy. When upgrading from the current `3.0.1` release to `develop` and building with `yarn`, a rather infamous error appears when trying to boot up Lock:

> Warning: addComponentAsRefTo(…): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component’s render method, or you have multiple copies of React loaded.

After some spelunking, there are indeed two React instances in `vendor.js`. Here's what seems to be happening:
- `auth0-lock` declares the dependency `"react": "^15.6.2"`
- `auth0-lock-passwordless` instead declares `"react": "^0.14.0"`
- Since the versions don't agree, both versions get added to `node_modules` when `yarn`'d.
- Broccoli builds both versions into `vendor.js`. Shenanigans ensue.

Parts of this are still a bit mysterious: this happens when creating a simple test app, but somehow, only one of the two `react`s get included in my production app build, and I'm not sure what's different between the two cases.

A temporary workaround for `yarn` users is to embed a `resolutions` block that forces `react` to one particular version, but that's not something we can do addon-side as `yarn` doesn't seem to look at `resolutions` inside dependencies (probably by design).

I don't think it's reasonable to ask users to do this when upgrading, though, and this will trip up everyone who's got a caret in their `ember-simple-auth-auth0` dependency declaration. So let's not do that. ;)

I'm still trying to figure out a resolution (heh). Even though passwordless mode is going to be [added to Lock](https://github.com/auth0/lock/pull/1070) at some point, there's no set timeline on that. Perhaps the solution for now is to make an  `auth0-lock-passwordless` PR to upgrade `react`, since that would eliminate the headache here.

Any thoughts?

[BTW, for those who are wondering "what does React have to do with an Ember addon?": Auth0's Lock is built with React. Just in case that saves a few brain cells.]

**Comment by dbinetti** [comment]
`auth0-lock-passwordless` has not seen a commit since June 2016, so any PR to that repo will almost certainly go nowhere.

**Comment by XaserAcheron** [comment]
Looks like someone's already [made a PR](https://github.com/auth0/lock-passwordless/pull/125) for exactly this. I'll leave a comment there just in case, since that'd be the most painless route.

**Comment by aaguiarz** [comment]
Would it be an option to ship a version without Passwordless? How much use of it do you think there's in the Ember community?

We have a version of Lock with Passwordless included that we are planning to ship in 3 to 4 weeks. The current one is not working in the OIDC conformant pipeline we are pushing, so I would not expect that a lot of ember users are actively using it.

**Comment by XaserAcheron** [comment]
It's a very tempting option -- no hacks, no mess. It's absolutely the way to go long-term, though 3 to 4 weeks isn't exactly "long-term" now, is it? ;)

Is there anyone out there on Passwordless that needs the latest stuff from the `develop` branch in the short term? If demand's not there, I'd say we could go ahead and release `v4.0.0` sans Passwordless, then update to `v4.1.0` once Lock gets the feature.

Even if we wait, I absolutely plan on upgrading and dropping Passwordless once Lock gets support. The question really is "do it now, or wait a bit?"

**Comment by aaguiarz** [comment]
Wait, as the API for Passwordless will be different than the current one, as it will be aligned with Lock 10's API.

**Comment by dbinetti** [comment]
Speaking bluntly, Auth0's recent history suggests 3-4 weeks is not a reliable estimate.  I want to believe that you've turned the corner on this, but am still skeptical.  

FWIW, I only use Passwordless, but not on `develop` -- I'm working off of one of @XaserAcheron's old forks and it gets the job done.

**Comment by aaguiarz** [comment]
FWIW, the changes are ready:

https://github.com/auth0/lock/tree/feature-add-pwdless
https://github.com/auth0/docs/pull/4870

We have to wrap up something else before shipping this, but it's done.

**Comment by roschaefer** [comment]
Wait! [We're using passwordless in production](https://rundfunk-mitbestimmen.de/). Actually, we're still on [my fork of this repo](https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/package.json#L59). I forgot to point back to the `develop` branch of the origin, but that's what I'm going to do.

**Comment by XaserAcheron** [comment]
Yup, seems like "Wait" is the winning verdict on the "drop Passwordless" front. FWIW, such a change would definitely be a major version bump, and at that point, it makes the most sense to go all the way and support Lock's new Passwordless integration when that arrives. Sounds like a good goal for `v4.0.0` at least.

I won't be pulling any trapdoor levers for the release, so no worries. Though that still leaves the open question of what to do about the dependency issue. I wouldn't want to cut a new release without addressing it... unless we tag it as a beta. Maybe that's not a bad call given we're all working off forks anyway. Thoughts?

**Comment by donaldwasserman** [comment]
Getting an alpha/beta release out at least gives everyone a common frame of reference to work against

**Comment by XaserAcheron** [comment]
Good thinking, though I think we've lucked out on that front, as this is resolved now -- whew!
