### ISSUE TITLE
Request: Remove dependence on bower

### ISSUE THREAD

**Issue by andrewcallahan** [auth0-community/ember-simple-auth-auth0#91]
As Ember is moving away from using bower, it would be great if this addon's dependencies could just use npm. Looking through previous commits, it looks like some work was done around this, but as of `3.0.1` running `ember install ember-simple-auth-auth0` still adds dependencies to the `bower.js` file.

**Comment by XaserAcheron** [comment]
Totally agree -- npm/yarn is the way to go.

The good news is that Bower has been fully ousted on the `develop` branch. The less-good news is there's still one issue (#89) that's blocking us from releasing a new version at the moment. Tricky stuff, but I'm tinkering with a potential workaround.

**Comment by andrewcallahan** [comment]
@XaserAcheron sounds good, thanks!

**Comment by XaserAcheron** [comment]
[v3.1.0](https://github.com/auth0-community/ember-simple-auth-auth0/releases/tag/v3.1.0) is released now, free of Bower dependencies. Should be good to go now!
