### ISSUE TITLE
Release Troubles

### ISSUE THREAD

**Issue by XaserAcheron** [auth0-community/ember-simple-auth-auth0#93]
The `v3.1.0` release is all ready to go, but there are a couple of issues stopping me from publishing it:
- It looks like I was added as an npm collaborator to [the old addon](https://www.npmjs.com/package/auth0-ember-simple-auth) by mistake, so I can't publish to NPM yet. Would someone mind adding me to the new one?
- `ember-cli-release` is configured to use [HubFlow](https://datasift.github.io/gitflow/), but part of its process involves pushing some commits to `develop` directly, which I can't do because the `develop` branch is protected on GitHub (it's enforcing a Travis status check). I lack permissions to temporarily relax the constraint, and that seems really un-ideal anyway. Any advice on this?

Paging @seawatts and @aaguiarz for assistance. Thanks in advance!

**Comment by dbinetti** [comment]
So who do I need to pester to help get this resolved?  I might not be the best coder, but man can I be a squeaky wheel...

**Comment by aaguiarz** [comment]
@XaserAcheron I apologize.. i missed this. You are an admin of the repo now, let me know if that works for you.

**Comment by lobo** [comment]
Thanks @aaguiarz ! @XaserAcheron you should be good to go.

**Comment by XaserAcheron** [comment]
Thanks! That's one block removed, though I still lack npm publish permissions. Are you able to take a look at that while you're here, @aaguiarz?

**Comment by aaguiarz** [comment]
On it

**Comment by aaguiarz** [comment]
@XaserAcheron what's your npm user?

**Comment by XaserAcheron** [comment]
https://www.npmjs.com/~xaser <-- pretty barebones, but I exist. :P

**Comment by aaguiarz** [comment]
You should are a collaborator on https://www.npmjs.com/package/ember-simple-auth-auth0 now

**Comment by XaserAcheron** [comment]
All good now. Thanks again!

v3.1.0 is live now, so I suppose this case is closed. ;)
