### ISSUE TITLE
SPA Ember.js: Typo in README file

### ISSUE THREAD

**Issue by paulioceano** [auth0-community/ember-simple-auth-auth0#98]
In the instruction in the README says:
 "The application will be served at `http://localhost:3000`."

![screenshot_1](https://user-images.githubusercontent.com/15818783/34683878-c2d8b66a-f479-11e7-8f12-66e1b4a21563.jpg)

But, after running ember serve, the console show me :

" Serving on http://localhost:4200/"

![screenshot_2](https://user-images.githubusercontent.com/15818783/34683957-f7487b7e-f479-11e7-97ce-8f5b843f2829.jpg)

The app can not be reached at http://localhost:3000, only when using http://localhost:4200.

![screenshot_4](https://user-images.githubusercontent.com/15818783/34684026-2af69cd0-f47a-11e7-948d-200b72d16b27.jpg)

**Comment by XaserAcheron** [comment]
Where are you seeing this? README.md correctly shows http://localhost:4200, and the posted README & browser screenshot contents don't match anything that's in this repo. Is there an external guide you're following somewhere?

**Comment by aaguiarz** [comment]
Hey @paulioceano let's skip this sample

@XaserAcheron , she's looking at the Quickstart https://auth0.com/docs/quickstart/spa/ember which at the bottom has a link to this repo. We'll build an embedded login sample in the https://github.com/auth0-community/auth0-ember-samples repo.

Thanks!

**Comment by XaserAcheron** [comment]
Ah, that explains it -- thanks @aaguiarz!

It may be a good idea to have one canon "quick start guide" hosted somewhere, since we've also got the one in this repo's README.md in addition to the official Auth0 guides. Easier to maintain if there's just one. :)
